#!/usr/bin/env python3
"""Inspect CodeRail runtime state and write docs/CODERAIL_STATUS.md.

This is a repo-local state surface. It reads CodeRail's markdown/jsonl files and
summarizes what is active, blocked, unverified, or unsafe to continue.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from datetime import datetime, timezone
import sys

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
import coordinate_check  # noqa: E402
import trace_doctor  # noqa: E402
import contract_check  # noqa: E402


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except FileNotFoundError:
        return ""


def first_section_value(text: str, header: str) -> str:
    m = re.search(rf"^##\s+{re.escape(header)}\s*\n(.*?)(?=^##\s|\Z)", text, re.S | re.M | re.I)
    if not m:
        return ""
    lines = [ln.strip("- ") for ln in m.group(1).splitlines() if ln.strip() and not ln.strip().startswith(">")]
    return lines[0] if lines else ""


def git_status(root: Path) -> str:
    try:
        out = subprocess.check_output(["git", "-C", str(root), "status", "--short"], text=True, stderr=subprocess.DEVNULL)
        return out.strip()
    except Exception:
        return "git status unavailable"


def load_events(root: Path) -> list[dict]:
    events = []
    log = root / "docs" / "TRACELOG.jsonl"
    if not log.exists():
        return events
    for raw in log.read_text(encoding="utf-8", errors="ignore").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            events.append(json.loads(raw))
        except json.JSONDecodeError:
            pass
    return events


def task_statuses(root: Path):
    text = read(root / "docs" / "TASKS.md")
    rows = []
    for header, body, status in coordinate_check.split_tasks(text):
        if "Example task" in header or "Copy template" in header:
            continue
        coord = coordinate_check.parse_coordinate(body) or {}
        rows.append({"id": header.split()[0], "header": header, "status": status, "coord": coord})
    return rows


def draft_statuses(root: Path):
    text = read(root / "docs" / "CONTRACTS.md")
    rows = []
    for header, body, status in contract_check.split_drafts(text):
        if "Example draft" in header:
            continue
        rows.append({"id": header.split()[0], "header": header, "status": status})
    return rows


def render(root: Path) -> tuple[str, str]:
    docs = root / "docs"
    ns = read(docs / "NORTH_STAR.md")
    outcome = first_section_value(ns, "Outcome") or "(unknown)"
    current_slice = first_section_value(ns, "Current Slice") or "(unknown)"
    tasks = task_statuses(root)
    drafts = draft_statuses(root)
    active = [t for t in tasks if t["status"] in {"[~]", "[ ]", "[!]"}]
    events = load_events(root)
    trace_severe, trace_warn = trace_doctor.check(events, docs / "TRACE_INDEX.md", docs / "TRACELOG.jsonl")

    verification_gaps = []
    for t in tasks:
        coord = t["coord"]
        v = (coord.get("v") or "").lower()
        if t["status"] == "[x]" and not any(k in v for k in ["passed", "manual", "pytest", "test", "harness"]):
            verification_gaps.append(f"{t['id']}: done task has weak V evidence")
    for item in trace_severe:
        if "verify" in item or "harness" in item:
            verification_gaps.append(item)

    trace_gaps = trace_warn + [x for x in trace_severe if x not in verification_gaps]
    handoff = read(docs / "HANDOFF.md")
    hm = re.search(r"Handoff Level:\s*([^\n]+)", handoff)
    handoff_level = hm.group(1).strip() if hm else "unknown"
    handoff_needs = "yes" if "needs" in handoff.lower() else "no"

    status = "blocked" if verification_gaps or trace_severe else ("warning" if trace_gaps or not outcome or active else "healthy")

    lines = []
    lines.append("# CodeRail Status")
    lines.append("")
    lines.append("> Generated by `scripts/inspect_state.py`. Prefer regenerating this file instead of editing it by hand.")
    lines.append("")
    lines.append(f"Generated at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    lines.append(f"Status: {status}")
    lines.append("")
    lines.append("## Current North Star")
    lines.append("")
    lines.append(f"- Outcome: {outcome}")
    lines.append(f"- Current Slice: {current_slice}")
    lines.append("")
    lines.append("## Active Coordinate")
    lines.append("")
    if active:
        t = active[0]
        coord = t["coord"]
        lines.append(f"- Task: {t['header']} ({t['status']})")
        lines.append(f"- G: {coord.get('g','(missing)') or '(missing)'}")
        lines.append(f"- T: {coord.get('t','(missing)') or '(missing)'}")
        lines.append(f"- S allowed: {coord.get('s_allowed','(missing)') or '(missing)'}")
        lines.append(f"- S forbidden: {coord.get('s_forbidden','(missing)') or '(missing)'}")
        lines.append(f"- V: {coord.get('v','(missing)') or '(missing)'}")
        lines.append(f"- X: {coord.get('x','(missing)') or '(missing)'}")
        lines.append(f"- P: {coord.get('p','(missing)') or '(missing)'}")
    else:
        lines.append("- none")
    lines.append("")
    lines.append("## Active Tasks")
    lines.append("")
    if active:
        for t in active:
            lines.append(f"- {t['header']} — {t['status']}")
    else:
        lines.append("- none")
    lines.append("")
    lines.append("## Draft Contracts")
    lines.append("")
    if drafts:
        for d in drafts:
            lines.append(f"- {d['header']} — {d['status']}")
    else:
        lines.append("- none")
    lines.append("")
    lines.append("## Verification Gaps")
    lines.append("")
    lines.append("- none" if not verification_gaps else "\n".join(f"- {x}" for x in verification_gaps))
    lines.append("")
    lines.append("## Trace Gaps")
    lines.append("")
    lines.append("- none" if not trace_gaps else "\n".join(f"- {x}" for x in trace_gaps[:20]))
    lines.append("")
    lines.append("## Handoff")
    lines.append("")
    lines.append(f"- Level: {handoff_level}")
    lines.append(f"- Needs update: {handoff_needs}")
    lines.append("")
    lines.append("## Recommended Next Action")
    lines.append("")
    if verification_gaps:
        lines.append("- Run `/coderail:done-gate` and fix verification gaps before marking done.")
    elif active:
        lines.append("- Continue the active task inside S and stop if X triggers.")
    elif drafts:
        lines.append("- Accept, revise, reject, or backlog the active contract draft before coding.")
    else:
        lines.append("- Run `/coderail:align` or `/coderail:contract-draft` for the next request.")
    lines.append("")
    lines.append("## Auto Commit")
    lines.append("")
    gs = git_status(root)
    if gs == "git status unavailable":
        lines.append("- Worktree: unknown")
        lines.append("- Git status unavailable; inspect the worktree before auto-commit.")
    elif gs:
        lines.append("- Worktree: dirty")
        lines.append("- Avoid `git add .` until changed files are matched to the active task S.")
        lines.append("- Run `scripts/closeout_check.py --target . --auto-commit` before stopping.")
    else:
        lines.append("- Worktree: clean")
        lines.append("- No commit boundary needed unless new work is started.")
    lines.append("")
    lines.append("## Git Status")
    lines.append("")
    lines.append("```text")
    lines.append(gs or "clean")
    lines.append("```")
    lines.append("")
    return status, "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Inspect CodeRail runtime state")
    ap.add_argument("--target", default=".")
    ap.add_argument("--write", action="store_true", help="Write docs/CODERAIL_STATUS.md")
    ap.add_argument("--no-write", action="store_true", help="Print only; do not write")
    args = ap.parse_args(argv)
    root = Path(args.target).resolve()
    status, text = render(root)
    if args.write or not args.no_write:
        docs = root / "docs"
        docs.mkdir(parents=True, exist_ok=True)
        (docs / "CODERAIL_STATUS.md").write_text(text + "\n", encoding="utf-8")
    print(text)
    return 1 if status == "blocked" else 0


if __name__ == "__main__":
    raise SystemExit(main())
