#!/usr/bin/env python3
"""Generate or update docs/TRACE_INDEX.md from docs/TRACELOG.jsonl.

Standard library only. Reads JSONL events, groups them, and writes a
human-readable index. If the log is empty, writes a clear empty template.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

EVENT_TYPES = {
    "intent", "align", "task", "decision", "research", "attempt",
    "change", "verify", "handoff", "lesson",
}


def load_events(log_path: Path) -> list:
    events = []
    if not log_path.exists():
        return events
    with log_path.open("r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                events.append(json.loads(raw))
            except json.JSONDecodeError as exc:
                print(f"warning: skipping invalid JSON on line {lineno}: {exc}", file=sys.stderr)
    return events


def _coord_summary(event: dict) -> str:
    coord = event.get("coordinate") or {}
    parts = []
    if coord.get("goal"):
        parts.append(f"G={coord['goal']}")
    if coord.get("task"):
        parts.append(f"T={coord['task']}")
    verify = coord.get("verify")
    if verify:
        v = verify[0] if isinstance(verify, list) else verify
        parts.append(f"V={v}")
    persist = coord.get("persist")
    if persist:
        p = persist if isinstance(persist, str) else ",".join(persist)
        parts.append(f"P={p}")
    return " ".join(parts)


def _event_line(event: dict) -> str:
    eid = event.get("id", "?")
    etype = event.get("type", "?")
    ts = event.get("ts", "")
    summary = (event.get("summary") or "").strip().replace("\n", " ")
    if len(summary) > 100:
        summary = summary[:97] + "..."
    coord = _coord_summary(event)
    suffix = f" [{coord}]" if coord else ""
    return f"- `{eid}` {etype} {ts} — {summary}{suffix}"


def render(events: list) -> str:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = []
    lines.append("# Trace Index")
    lines.append("")
    lines.append("> Generated by `scripts/trace_index.py`. Do not edit by hand; rerun")
    lines.append("> the script after appending events to `docs/TRACELOG.jsonl`.")
    lines.append(">")
    lines.append("> This index is the human-readable view of `TRACELOG.jsonl`. The JSONL")
    lines.append("> file is the source of truth. See `references/TRACE_GRAPH.md` for the schema.")
    lines.append("")
    lines.append(f"Generated at: {now}")
    lines.append(f"Event count: {len(events)}")
    lines.append("")

    if not events:
        lines.append("## Current Active Chain")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## Recent Events")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## By Task")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## By File")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## By North Star")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## Orphan Nodes")
        lines.append("")
        lines.append("Events that cannot be linked to a task, north star, or file.")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        lines.append("## Verification Gaps")
        lines.append("")
        lines.append("`change` events without a linked `verify` event, or `done` tasks without verify.")
        lines.append("")
        lines.append("- (empty)")
        lines.append("")
        return "\n".join(lines)

    # Current Active Chain: tasks that are open/doing (not done) referenced recently.
    task_events = defaultdict(list)
    file_events = defaultdict(list)
    ns_events = defaultdict(list)
    changes_without_verify = []
    change_ids = set()
    verify_for_change = defaultdict(list)

    for ev in events:
        t = ev.get("task")
        if t:
            task_events[t].append(ev)
        ns = ev.get("north_star")
        if ns:
            ns_events[ns].append(ev)
        for f in (ev.get("files") or []) + (ev.get("modifies") or []):
            file_events[f].append(ev)
        if ev.get("type") == "change":
            change_ids.add(ev.get("id"))
        if ev.get("type") == "verify":
            task = ev.get("task")
            if task:
                verify_for_change[task].append(ev)

    for ev in events:
        if ev.get("type") == "change":
            task = ev.get("task")
            linked_verify = []
            if task and task in verify_for_change:
                linked_verify = verify_for_change[task]
            if not linked_verify:
                changes_without_verify.append(ev)

    orphans = []
    for ev in events:
        if ev.get("type") in {"intent", "align"}:
            continue
        if ev.get("task") or ev.get("north_star") or ev.get("files"):
            continue
        orphans.append(ev)

    # Current Active Chain: most recent open task per task id.
    lines.append("## Current Active Chain")
    lines.append("")
    open_tasks = []
    for task, evs in task_events.items():
        statuses = [e.get("status") for e in evs if e.get("status")]
        latest = evs[-1]
        if not any(s in {"done", "rejected", "superseded"} for s in statuses):
            open_tasks.append((task, latest))
    if open_tasks:
        for task, latest in open_tasks:
            lines.append(_event_line(latest))
    else:
        lines.append("- (none open)")
    lines.append("")

    lines.append("## Recent Events")
    lines.append("")
    recent = sorted(events, key=lambda e: e.get("ts", ""), reverse=True)[:15]
    for ev in recent:
        lines.append(_event_line(ev))
    lines.append("")

    lines.append("## By Task")
    lines.append("")
    for task in sorted(task_events):
        lines.append(f"### {task}")
        for ev in task_events[task]:
            lines.append(_event_line(ev))
        lines.append("")
    if not task_events:
        lines.append("- (none)")
        lines.append("")

    lines.append("## By File")
    lines.append("")
    for f in sorted(file_events):
        count = len(file_events[f])
        lines.append(f"- `{f}` ({count})")
    if not file_events:
        lines.append("- (none)")
    lines.append("")

    lines.append("## By North Star")
    lines.append("")
    for ns in sorted(ns_events):
        count = len(ns_events[ns])
        lines.append(f"- `{ns}` ({count})")
    if not ns_events:
        lines.append("- (none)")
    lines.append("")

    lines.append("## Orphan Nodes")
    lines.append("")
    lines.append("Events that cannot be linked to a task, north star, or file.")
    lines.append("")
    if orphans:
        for ev in orphans:
            lines.append(_event_line(ev))
    else:
        lines.append("- (none)")
    lines.append("")

    lines.append("## Verification Gaps")
    lines.append("")
    lines.append("`change` events without a linked `verify` event, or `done` tasks without verify.")
    lines.append("")
    if changes_without_verify:
        for ev in changes_without_verify:
            lines.append(_event_line(ev))
    else:
        lines.append("- (none)")
    lines.append("")

    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/TRACE_INDEX.md")
    parser.add_argument("--target", default=".", help="Repository root containing docs/")
    args = parser.parse_args(argv)

    target = Path(args.target).resolve()
    if not target.exists():
        print(f"target does not exist: {target}", file=sys.stderr)
        return 2

    docs = target / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    log_path = docs / "TRACELOG.jsonl"
    index_path = docs / "TRACE_INDEX.md"

    events = load_events(log_path)
    text = render(events)
    index_path.write_text(text, encoding="utf-8")
    print(f"wrote {index_path} ({len(events)} events)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
