#!/usr/bin/env python3
"""Generate docs/TRACE_INDEX.md from docs/TRACELOG.jsonl."""
from __future__ import annotations
import argparse, json, sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

def load_events(log_path: Path):
    events=[]
    if not log_path.exists(): return events
    for lineno, raw in enumerate(log_path.read_text(encoding='utf-8').splitlines(),1):
        raw=raw.strip()
        if not raw: continue
        try: events.append(json.loads(raw))
        except json.JSONDecodeError as e: print(f"warning: skip invalid JSON line {lineno}: {e}", file=sys.stderr)
    return events

def coord_summary(ev):
    c=ev.get('coordinate') or {}; out=[]
    if c.get('goal'): out.append(f"G={c['goal']}")
    if c.get('task'): out.append(f"T={c['task']}")
    v=c.get('verify')
    if v: out.append('V=' + (v[0] if isinstance(v,list) else str(v)))
    p=c.get('persist')
    if p: out.append('P=' + (','.join(p) if isinstance(p,list) else str(p)))
    return ' '.join(out)

def ev_line(ev):
    s=(ev.get('summary') or '').replace('\n',' ').strip()
    if len(s)>110: s=s[:107]+'...'
    suffix=f" [{coord_summary(ev)}]" if coord_summary(ev) else ''
    return f"- `{ev.get('id','?')}` {ev.get('type','?')} {ev.get('ts','')} — {s}{suffix}"

def render(events):
    lines=['# Trace Index','',"> Generated by `python .coderail/coderail.py trace-index`; do not edit by hand.",'',f"Generated at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",f"Event count: {len(events)}",'']
    task_events=defaultdict(list); file_events=defaultdict(list); ns_events=defaultdict(list); verify_by_task=defaultdict(list)
    for ev in events:
        if ev.get('task'): task_events[ev['task']].append(ev)
        if ev.get('north_star'): ns_events[ev['north_star']].append(ev)
        for f in (ev.get('files') or []) + (ev.get('modifies') or []): file_events[f].append(ev)
        if ev.get('type')=='verify' and ev.get('task'): verify_by_task[ev['task']].append(ev)
    changes_without_verify=[ev for ev in events if ev.get('type')=='change' and ev.get('task') not in verify_by_task and not ev.get('validated_by')]
    orphans=[ev for ev in events if ev.get('type') not in {'intent','align'} and not (ev.get('task') or ev.get('north_star') or ev.get('files'))]
    lines += ['## Current Active Chain','']
    open_items=[]
    for task, evs in task_events.items():
        statuses=[e.get('status') for e in evs if e.get('status')]
        if not any(s in {'done','rejected','superseded'} for s in statuses): open_items.append(evs[-1])
    lines += [ev_line(e) for e in open_items] or ['- (none open)']; lines.append('')
    lines += ['## Recent Events',''] + ([ev_line(e) for e in sorted(events,key=lambda x:x.get('ts',''),reverse=True)[:15]] or ['- (empty)']) + ['']
    lines += ['## By Task','']
    if task_events:
        for t in sorted(task_events):
            lines.append(f"### {t}"); lines += [ev_line(e) for e in task_events[t]]; lines.append('')
    else: lines += ['- (none)','']
    lines += ['## By File',''] + ([f"- `{f}` ({len(file_events[f])})" for f in sorted(file_events)] or ['- (none)']) + ['']
    lines += ['## By North Star',''] + ([f"- `{n}` ({len(ns_events[n])})" for n in sorted(ns_events)] or ['- (none)']) + ['']
    lines += ['## Orphan Nodes','', 'Events that cannot be linked to a task, north star, or file.',''] + ([ev_line(e) for e in orphans] or ['- (none)']) + ['']
    lines += ['## Verification Gaps','', '`change` events without a linked verify event or validated_by edge.',''] + ([ev_line(e) for e in changes_without_verify] or ['- (none)']) + ['']
    return '\n'.join(lines)

def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument('--target', default='.')
    args=p.parse_args(argv); root=Path(args.target).resolve(); docs=root/'docs'; docs.mkdir(parents=True, exist_ok=True)
    events=load_events(docs/'TRACELOG.jsonl'); text=render(events); (docs/'TRACE_INDEX.md').write_text(text, encoding='utf-8')
    print(f"wrote {docs/'TRACE_INDEX.md'} ({len(events)} events)")
    return 0
if __name__=='__main__': raise SystemExit(main())
